use mobile

SELECT * FROM MOBILE_DATA ;

---> Q1 CHECK MOBILE FEATURS & PRICE LIST

SELECT PHONE_NAME , PRICE FROM MOBILE_DATA ;

----> Q2 FIND OUT THE PRICE OF MOST EXPENSIVE PHONES 


SELECT TOP 5  * FROM MOBILE_DATA 
ORDER BY PRICE DESC;


----> Q3 FIND OUT THE 5 MOST CHEPEST PHONES
 
SELECT TOP 5 * FROM MOBILE_DATA
ORDER BY PRICE ;

---> Q 4 LIST OF THE TOP 5 SAMSUNG PHONES WITH PRICE & ALL FEATURES 

SELECT TOP 5 * FROM MOBILE_DATA 
WHERE BRANDS ='SAMSUNG'
ORDER BY PRICE DESC ;

---> Q5 MUST HAVE THE ANDROID PHOEN LIST TOP 10 HIGH PRICE ANDRIOD PHONES 

SELECT TOP 10 * FROM MOBILE_DATA 
WHERE OPERATING_SYSTEM_TYPE = 'ANDROID'
ORDER BY PRICE DESC ;

---> Q6 MUST HAVE THE ANDROID PHOEN LIST  10 LOW PRICE ANDRIOD PHONES 

SELECT TOP 10 * FROM MOBILE_DATA 
WHERE OPERATING_SYSTEM_TYPE = 'ANDROID'
ORDER BY PRICE  ;

--->Q7 TOP 5 HIGH PRICE IOS PHONES 

SELECT TOP 5 * FROM MOBILE_DATA 
WHERE OPERATING_SYSTEM_TYPE = 'IOS'
ORDER BY PRICE DESC ;

---> Q8 TOP 5 LOW PRICE IOS PHONES 
SELECT TOP 5 * FROM MOBILE_DATA 
WHERE OPERATING_SYSTEM_TYPE = 'IOS'
ORDER BY PRICE  ;

---> Q9 WRITE A QUERY WHICH PHONE SUPPORT 5G AND ALSO TOP 5 PHONES WITH THE 5G SUPPORT 

SELECT TOP 5 * FROM MOBILE_DATA 
WHERE [Availability_5G] = 'YES'
ORDER BY PRICE DESC  ;


----> Q10 TOTAL PRICE OF ALL MOBILE WITH BRAND NAMES

SELECT BRANDS , SUM(PRICE) AS 'TOTAL_PRICE' FROM MOBILE_DATA 
GROUP BY BRANDS
ORDER BY SUM(PRICE) DESC ;





